lpar: Fix body issue with STOP operation
This fixes the following problem:

$ zhmc -o json lpar stop --yes --allow-status-exceptions CPC LPAR
Error: HTTPError: 400,4: A content-length was specified but a body was not
       expected by this provider.
       [POST /api/logical-partitions/xxx/operations/stop]

According to the HMC REST API 2.15, the LPAR STOP operation doesn't expect
any body, not even an empty one.

See "Hardware Management Console Web Services API Version 2.15.0",
"Chapter 11. Core IBM Z resources", "Stop Logical Partition".

Signed-off-by: Alexander Egorenkov <egorenar@linux.ibm.com>